/*
 * gameResources.js
 * 
 * Defines assets to be loaded.
 *
 * Author: Andrew Ford
 */

var gameResources =
[
    { name: "player", type: "image", src: "data/player.png" },
    { name: "dude01", type: "image", src: "data/dude01.png" },
    { name: "dude02", type: "image", src: "data/dude02.png" },
    { name: "dude03", type: "image", src: "data/dude03.png" },
    { name: "bloodsplat", type: "image", src: "data/bloodsplat.png" },
    { name: "heart", type: "image", src: "data/heart.png" },
    { name: "burned", type: "image", src: "data/burned.png" },
    { name: "lazer", type: "image", src: "data/lazer.png" },
    { name: "jump", type: "image", src: "data/jump.png" },
    { name: "splash", type: "image", src: "data/splash.png" },
    { name: "splash_cta", type: "image", src: "data/splash_cta.png" },
    { name: "splash_title", type: "image", src: "data/splash_title.png" },
    { name: "end_background", type: "image", src: "data/end_background.png" },
    { name: "end_great", type: "image", src: "data/end_great.png" },
    { name: "end_terrible", type: "image", src: "data/end_terrible.png" },
    { name: "area01_level_tiles", type: "image", src: "data/area01_level_tiles.png" },
    { name: "area02_level_tiles", type: "image", src: "data/area02_level_tiles.png" },
    { name: "area03_level_tiles", type: "image", src: "data/area03_level_tiles.png" },
    { name: "16x16_font", type: "image", src: "data/16x16_font.png" },
    { name: "32x32_font", type: "image", src: "data/32x32_font.png" },
    { name: "64x64_font", type: "image", src: "data/64x64_font.png" },
    { name: "hud_hp", type: "image", src: "data/hud_hp.png" },
    { name: "hud_lives", type: "image", src: "data/hud_lives.png" },
    { name: "collision_tiles", type: "image", src: "data/collision_tiles.png" },
    { name: "area01_parallax1", type: "image", src: "data/area01_parallax1.png" },
    { name: "area02_parallax1", type: "image", src: "data/area02_parallax1.png" },
    { name: "area03_parallax1", type: "image", src: "data/area03_parallax1.png" },
    { name: "area03_parallax2", type: "image", src: "data/area03_parallax2.png" },
    { name: "level1", type: "tmx", src: "data/level1.tmx" },
    { name: "level2", type: "tmx", src: "data/level2.tmx" },
    { name: "level3", type: "tmx", src: "data/level3.tmx" },
    { name: "level4", type: "tmx", src: "data/level4.tmx" },
    { name: "level5", type: "tmx", src: "data/level5.tmx" },
    { name: "level6", type: "tmx", src: "data/level6.tmx" },
    { name: "level7", type: "tmx", src: "data/level7.tmx" },
    { name: "level9", type: "tmx", src: "data/level9.tmx" },
    { name: "djump", type: "audio", src: "data/", channels : 2 },
    { name: "grab", type: "audio", src: "data/", channels : 2 },
    { name: "hurt", type: "audio", src: "data/", channels : 2 },
    { name: "jump", type: "audio", src: "data/", channels : 2 },
    { name: "off", type: "audio", src: "data/", channels : 2 },
    { name: "lazer", type: "audio", src: "data/", channels : 2 },
    { name: "ready", type: "audio", src: "data/", channels : 2 },
    { name: "lazerdeath", type: "audio", src: "data/", channels : 2 },
    { name: "stompdeath", type: "audio", src: "data/", channels : 2 },
    { name: "death", type: "audio", src: "data/", channels : 2 },
    { name: "ld23-theme", type: "audio", src: "data/", channels : 2 },
    { name: "ld23-mars", type: "audio", src: "data/", channels : 2 },
    { name: "ld23-air", type: "audio", src: "data/", channels : 2 },
    { name: "ld23-space", type: "audio", src: "data/", channels : 2 },
];
